### PR TITLE
Merging late bugs in password and transaction functionality

### PR DESCRIPTION
**Pull request by bermed28**
PR to merge transaction bug fixes to password bug fixes

### CODE REVIEW

**Comment by bermed28** [comment]
Once this PR is approved and merged, this has to go to fernando/frontend so we can finally approve PR #19

**Review by bermed28 — COMMENTED** [review]
LGTM, stll need +1 from reviewers

**Review by Chris36021 — APPROVED** [review]
Everything seems to be in order

**Review by gabrieldiazmorro — APPROVED** [review]
LGTM

**Pull request merged**
